#pragma once                                                                                                    
#define KERNELDRIVER                                                                                                                                                                                                                                                                                                                                                                       
#define KDRIVER_MAJOR_VERSION 1                                                                                                                                                                                                                                                                                                                                                                       
#define KDRIVER_MINOR_VERSION 0                                                                                                                                                                                                                                                                                                                                                                       
#define KDRIVER_BUILD_VERSION 721 
//Which software version we want to compile for                                                                                                                                                                                                                                                                                                                                                                       
#define SOFTWARE_VERSION_NA                                                                                                                                                                                                                                                                                                                                                                       
#ifdef VERSION_505                                                                                                                                                                                                                                                                                                                     
#define SOFTWARE_VERSION_STR "5.05"                                                                                                                                                                                                                                                                                                                                                                       
#define SOFTWARE_VERSION_505                                                                                                                                                                                                                                                                                                                                                                       
#undef SOFTWARE_VERSION_NA                                                                                                                                                                                                                                                                                                                                                                       
#endif                                                                                                                                                                                                                                                                                                                                                                       
#ifdef VERSION_672                                                                                                                                                                                                                                                                                                                     
#define SOFTWARE_VERSION_STR "6.72"                                                                                                                                                                                                                                                                                                                                                                        
#define SOFTWARE_VERSION_672                                                                                                                                                                                                                                                                                                                                                                       
#undef SOFTWARE_VERSION_NA                                                                                                                                                                                                                                                                                                                                                                       
#endif                                                                                                                                                                                                                                                                                                                                                                       
#ifdef VERSION_702                                                                                                                                                                                                                                                                                                                     
#define SOFTWARE_VERSION_STR "7.02"                                                                                                                                                                                                                                                                                                                                                                        
#define SOFTWARE_VERSION_702                                                                                                                                                                                                                                                                                                                                                                       
#undef SOFTWARE_VERSION_NA                                                                                                                                                                                                                                                                                                                                                                       
#endif                                                                                                                                                                                                                                                                                                                                                                       
#ifdef VERSION_755                                                                                                                                                                                                                                                                                                                      
#define SOFTWARE_VERSION_STR "7.55"                                                                                                                                                                                                                                                                                                                                                                       
#define SOFTWARE_VERSION_755                                                                                                                                                                                                                                                                                                                                                                       
#undef SOFTWARE_VERSION_NA                                                                                                                                                                                                                                                                                                                                                                       
#endif                                                                                                                                                                                                                                                                                                                                                                       
#ifdef VERSION_900                                                                                                                                                                                                                                                                                                                     
#define SOFTWARE_VERSION_STR "9.00"                                                                                                                                                                                                                                                                                                                                                                       
#define SOFTWARE_VERSION_900                                                                                                                                                                                                                                                                                                                                                                       
#undef SOFTWARE_VERSION_NA                                                                                                                                                                                                                                                                                                                                                                       
#endif                                                                                                                                                                                                                                                                                                                       
